// frontend-vue/src/components/TaskForm.vue
<template>
  <div className="task-form">
    <div className="form-group">
      <input v-model="title" placeholder="Task title" />
      <input v-model="description" placeholder="Description (optional)" />
      <button @click="handleAdd" aria-label="Add task">
        <i className="fas fa-plus"></i>
      </button>
    </div>
    <div v-if="error" className="error-message" role="alert">{{ error }}</div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useToast } from 'vue-toastification';
import { useTaskStore } from '../stores/auth';
import './styles/TaskForm.css';

const toast = useToast();

const taskStore = useTaskStore();
const title = ref('');
const description = ref('');
const error = ref('');

const handleAdd = async () => {
  if (!title.value.trim()) {
    toast.error('Title is required');
    return;
  }
  try {
    await taskStore.addTask(title.value, description.value);
    toast.success('Task added successfully!');
    title.value = '';
    description.value = '';
  } catch (error) {
    toast.error('Failed to add task');
  }
};
</script>

// frontend/src/components/TaskForm.tsx
import React, { useState } from 'react';
import toast from 'react-hot-toast';
import { addTask } from '../services/api';
import './styles/TaskForm.css';

const TaskForm: React.FC<{ todoListId: number; onAdd: () => void }> = ({ todoListId, onAdd }) => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [error, setError] = useState('');

  const handleSubmit = async () => {
    if (!title.trim()) {
      toast.error('Title is required');
      return;
    }
    try {
      await addTask(title, description, todoListId);
      toast.success('Task added successfully!');
      setTitle('');
      setDescription('');
      onAdd();
    } catch (err) {
      toast.error('Failed to add task');
    }
  };

  return (
    <div className="task-form">
      <div className="form-group">
        <input
          value={title}
          onChange={e => setTitle(e.target.value)}
          placeholder="Title"
        />
        <input
          value={description}
          onChange={e => setDescription(e.target.value)}
          placeholder="Description (optional)"
        />
        <button className="add-btn" onClick={handleSubmit}>
          <i className="fas fa-plus"></i>
        </button>
      </div>
      {error && <div className="error-message">{error}</div>}
    </div>
  );
};

export default TaskForm;
