// frontend/src/components/TodoListSelector.tsx
import React, { useState, useEffect } from 'react';
import { getTodoLists, addTodoList, updateTodoList, deleteTodoList } from '../services/api';
import toast from 'react-hot-toast';
import './styles/TodoListSelector.css';

interface TodoList {
  id: number;
  name: string;
}

const TodoListSelector: React.FC<{ onSelect: (id: number) => void }> = ({ onSelect }) => {
  const [lists, setLists] = useState<TodoList[]>([]);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [newListName, setNewListName] = useState('');
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editName, setEditName] = useState('');

  useEffect(() => {
    fetchLists();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const fetchLists = async () => {
    const data = await getTodoLists();
    setLists(data);
    if (data.length > 0 && (!selectedId || !data.find((list : TodoList) => list.id === selectedId))) {
      setSelectedId(data[0].id);
      onSelect(data[0].id);
    }
  };

  const handleAdd = async () => {
    if (!newListName) {
      toast.error('List name is required');
      return;
    }
    try {
      await addTodoList(newListName);
      toast.success('List added successfully!');
      setNewListName('');
      fetchLists();
    } catch (error) {
      toast.error('Failed to add list');
    }
  };

  const handleUpdate = async (id: number) => {
    try {
      await updateTodoList(id, editName);
      toast.success('List updated successfully!');
      setEditingId(null);
      fetchLists();
    } catch (error) {
      toast.error('Failed to update list');
    }
  };

  const handleDelete = async (id: number) => {
    try {
      await deleteTodoList(id);
      toast.success('List deleted successfully!');
      fetchLists();
      if (selectedId === id) {
        setSelectedId(lists[0]?.id || null);
        onSelect(lists[0]?.id || 0);
      }
    } catch (error) {
      toast.error('Failed to delete list');
    }
  };

  const startEdit = (list: TodoList) => {
    setEditingId(list.id);
    setEditName(list.name);
  };

  const cancelEdit = () => {
    setEditingId(null);
    setEditName('');
  };

  return (
    <div className="todo-list-selector">
      <h3>Lists</h3>
      <select
        id="todolist"
        aria-label="Select a to-do list"
        name="todolist"
        value={selectedId || ''}
        onChange={e => {
          setSelectedId(Number(e.target.value));
          onSelect(Number(e.target.value));
        }}
      >
        {lists.map(list => (
          <option id={`todolist-${list.id}`} key={list.id} value={list.id}>
            {list.name}
          </option>
        ))}
      </select>
      <div className="add-form">
        <input
          value={newListName}
          onChange={e => setNewListName(e.target.value)}
          placeholder="Add a list"
        />
        <button onClick={handleAdd} aria-label="Add list">
          <i className="fas fa-plus"></i>
        </button>
      </div>
      {selectedId && (
        <div className="list-actions">
          {editingId === selectedId ? (
            <div className="action-buttons">
              <input
                value={editName}
                onChange={e => setEditName(e.target.value)}
              />
              <button onClick={() => handleUpdate(selectedId)}
                className="save-btn"
                aria-label="Save list">
                <i className="fas fa-save"></i>
              </button>
              <button onClick={cancelEdit} className="cancel-btn" aria-label="Cancel edit">
                <i className="fas fa-times"></i>
              </button>
            </div>
          ) : (
            <div className="action-buttons">
              <button
                onClick={() => startEdit(lists.find(list => list.id === selectedId)!)}
                className="edit-btn"
                aria-label="Edit selected list"
              >
                <i className="fas fa-edit"></i>
              </button>
              <button onClick={() => handleDelete(selectedId)} className="delete-btn" aria-label="Delete selected list">
                <i className="fas fa-trash"></i>
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default TodoListSelector;

// frontend-vue/src/components/TodoListSelector.vue
<template>
  <div className="todo-list-selector">
    <h3>Lists</h3>
    <select
      v-model="taskStore.selectedListId"
      @change="taskStore.setSelectedListId(taskStore.selectedListId)"
    >
      <option v-for="list in taskStore.todoLists" :key="list.id" :value="list.id">
        {{ list.name }}
      </option>
    </select>
    <div className="add-form">
      <input
        v-model="newListName"
        placeholder="Add a list"
      />
      <button @click="handleAdd" aria-label="Add list">
        <i className="fas fa-plus"></i>
      </button>
    </div>
    <div className="list-actions" v-if="taskStore.selectedListId">
      <template v-if="editingId === taskStore.selectedListId">
        <div className="edit-form">
          <input v-model="editName" />
          <button @click="handleUpdate(taskStore.selectedListId)" className="save-btn" aria-label="Save list">
            <i className="fas fa-save"></i>
          </button>
          <button @click="cancelEdit" className="cancel-btn" aria-label="Cancel edit">
            <i className="fas fa-times"></i>
          </button>
        </div>
      </template>
      <template v-else>
        <div className="action-buttons">
          <button @click="startEdit(taskStore.todoLists.find(list => list.id === taskStore.selectedListId)!)" className="edit-btn" aria-label="Edit selected list">
            <i className="fas fa-edit"></i>
          </button>
          <button @click="handleDelete(taskStore.selectedListId)" className="delete-btn" aria-label="Delete selected list">
            <i className="fas fa-trash"></i>
          </button>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useToast } from 'vue-toastification';
import { useTaskStore } from '../stores/auth';
import './styles/TodoListSelector.css';

const toast = useToast();

const taskStore = useTaskStore();
const newListName = ref('');
const editingId = ref<number | null>(null);
const editName = ref('');

onMounted(() => taskStore.fetchTodoLists());

const handleAdd = async () => {
  if (!newListName.value.trim()) {
    toast.error('List name is required');
    return;
  }
  try {
    await taskStore.addTodoList(newListName.value);
    toast.success('Todo list added successfully!');
    newListName.value = '';
  } catch (error) {
    toast.error('Failed to add todo list');
  }
};

const handleUpdate = async (id: number) => {
  try {
    await taskStore.updateTodoList(id, editName.value);
    toast.success('Todo list updated successfully!');
    editingId.value = null;
  } catch (error) {
    toast.error('Failed to update todo list');
  }
};

const handleDelete = async (id: number) => {
  try {
    await taskStore.deleteTodoList(id);
    toast.success('Todo list deleted successfully!');
    await taskStore.fetchTasks();
  } catch (error) {
    toast.error('Failed to delete todo list');
  }
};

const startEdit = (list: { id: number; name: string }) => {
  editingId.value = list.id;
  editName.value = list.name;
};

const cancelEdit = () => {
  editingId.value = null;
  editName.value = '';
};
</script>
