// frontend-vue/src/App.vue
<template>
  <div className="app-container">
    <div className="header">
      <h1>To-Do App (Vue)</h1>
      <button @click="toggleDarkMode" className="theme-toggle">
        <i :class="isDarkMode ? 'fas fa-sun' : 'fas fa-moon'"></i>
        {{ isDarkMode ? " Light Mode" : " Dark Mode" }}
      </button>
    </div>
    <Login v-if="!authStore.token" />
    <template v-else>
      <TodoListSelector />
      <TaskList v-if="taskStore.selectedListId" />
      <button @click="authStore.logout" className="logout-btn">Logout</button>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import Login from "./components/Login.vue";
import TaskList from "./components/TaskList.vue";
import TodoListSelector from "./components/TodoListSelector.vue";
import { useAuthStore } from "./stores/auth";
import { useTaskStore } from "./stores/auth";
import "./components/styles/App.css";

const authStore = useAuthStore();
const taskStore = useTaskStore();
const isDarkMode = ref(localStorage.getItem("darkMode") === "true");

onMounted(() => {
  document.body.classList.toggle("dark", isDarkMode.value);
});

const toggleDarkMode = () => {
  isDarkMode.value = !isDarkMode.value;
  localStorage.setItem("darkMode", isDarkMode.value.toString());
  document.body.classList.toggle("dark", isDarkMode.value);
};
</script>

// frontend/src/App.tsx
import React, { useState } from 'react';
import Login from './components/Login';
import TaskList from './components/TaskList';
import TodoListSelector from './components/TodoListSelector';
import './components/styles/App.css';

const App: React.FC = () => {
  const [token, setToken] = useState(localStorage.getItem('token'));
  const [selectedListId, setSelectedListId] = useState(0);
    
  const handleLogin = (newToken: string) => {
    setToken(newToken);
  };

  const [isDarkMode, setIsDarkMode] = useState(() => {
    const saved = localStorage.getItem('darkMode');
    console.log('Saved dark mode:', saved);
    if (!saved) return false;
    const newMode = JSON.parse(saved);
    document.body.classList.toggle('dark', newMode);
    return newMode;
  });

  const toggleDarkMode = () => {
    setIsDarkMode((prev: Boolean) => {
      const newMode = !prev;
      localStorage.setItem('darkMode', JSON.stringify(newMode));
      document.body.classList.toggle('dark', newMode);
      return newMode;
    });
  };

  return (
    <div className="app-container">
      {token ? (
        <>
          <div className="header">
            <h1>To-Do App</h1>
            <button onClick={toggleDarkMode} className="theme-toggle">
              <i className={isDarkMode ? 'fas fa-sun' : 'fas fa-moon'}></i>
              {isDarkMode ? ' Light Mode' : ' Dark Mode'}
            </button>
          </div>
          <TodoListSelector onSelect={setSelectedListId} />
          {selectedListId > 0 && (
            <>
              <TaskList todoListId={selectedListId} />
            </>
          )}
          <button
            onClick={() => {
              localStorage.removeItem('token');
              setToken(null);
            }}
            className="logout-btn"
          >
            Logout
          </button>
        </>
      ) : (
        <Login onLogin={handleLogin} />
      )}
    </div>
  );
};

export default App;
